print("Hi Good morning all")
print("Today is 22nd September 2024")
print("We had DevOps class at 8AM")
print("We all came 10mins late to the class")
print("Gagan did not attend online class")
print("We were thought about executing a python file from github")
print("Automatic built")
print("SMPT using Jenkins")
print("and built failures")
